<log4j:event logger="IQVIABadAPI.Controllers.HomeController" timestamp="1524477255817" level="ERROR" thread="9"><log4j:message><![CDATA[System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at IQVIABadAPI.Controllers.HomeController.LoadTweets() in C:\Projects\IQIVIABadAPI\IQIVIABadAPI\Controllers\HomeController.cs:line 39]]></log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="IN45207575W1" /><log4j:data name="log4japp" value="/LM/W3SVC/2/ROOT-1-131689507450689868" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="MEA\Arun.Viswanath" /><log4j:data name="log4net:HostName" value="IN45207575W1" /></log4j:properties><log4j:throwable>System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)</log4j:throwable></log4j:event>
<log4j:event logger="IQVIABadAPI.Controllers.HomeController" timestamp="1524477554502" level="ERROR" thread="5"><log4j:message><![CDATA[System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at IQVIABadAPI.Controllers.HomeController.LoadTweets() in C:\Projects\IQIVIABadAPI\IQIVIABadAPI\Controllers\HomeController.cs:line 39]]></log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="IN45207575W1" /><log4j:data name="log4japp" value="/LM/W3SVC/2/ROOT-1-131689510799422898" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="MEA\Arun.Viswanath" /><log4j:data name="log4net:HostName" value="IN45207575W1" /></log4j:properties><log4j:throwable>System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)</log4j:throwable></log4j:event>
<log4j:event logger="IQVIABadAPI.Controllers.HomeController" timestamp="1524479314923" level="ERROR" thread="21"><log4j:message><![CDATA[System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at IQVIABadAPI.Controllers.HomeController.LoadTweets() in C:\Projects\IQIVIABadAPI\IQIVIABadAPI\Controllers\HomeController.cs:line 39]]></log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="IN45207575W1" /><log4j:data name="log4japp" value="/LM/W3SVC/2/ROOT-1-131689510799422898" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="MEA\Arun.Viswanath" /><log4j:data name="log4net:HostName" value="IN45207575W1" /></log4j:properties><log4j:throwable>System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)</log4j:throwable></log4j:event>
<log4j:event logger="IQVIABadAPI.Controllers.HomeController" timestamp="1524479392009" level="ERROR" thread="14"><log4j:message><![CDATA[System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at IQVIABadAPI.Controllers.HomeController.LoadTweets() in C:\Projects\IQIVIABadAPI\IQIVIABadAPI\Controllers\HomeController.cs:line 39]]></log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="IN45207575W1" /><log4j:data name="log4japp" value="/LM/W3SVC/2/ROOT-1-131689510799422898" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="MEA\Arun.Viswanath" /><log4j:data name="log4net:HostName" value="IN45207575W1" /></log4j:properties><log4j:throwable>System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)</log4j:throwable></log4j:event>
<log4j:event logger="IQVIABadAPI.Controllers.HomeController" timestamp="1524479840569" level="ERROR" thread="25"><log4j:message><![CDATA[System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at IQVIABadAPI.Controllers.HomeController.LoadTweets() in C:\Projects\IQIVIABadAPI\IQIVIABadAPI\Controllers\HomeController.cs:line 39]]></log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="IN45207575W1" /><log4j:data name="log4japp" value="/LM/W3SVC/2/ROOT-1-131689510799422898" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="MEA\Arun.Viswanath" /><log4j:data name="log4net:HostName" value="IN45207575W1" /></log4j:properties><log4j:throwable>System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)</log4j:throwable></log4j:event>
<log4j:event logger="IQVIABadAPI.Controllers.HomeController" timestamp="1524479850044" level="ERROR" thread="22"><log4j:message><![CDATA[System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at IQVIABadAPI.Controllers.HomeController.LoadTweets() in C:\Projects\IQIVIABadAPI\IQIVIABadAPI\Controllers\HomeController.cs:line 39]]></log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="IN45207575W1" /><log4j:data name="log4japp" value="/LM/W3SVC/2/ROOT-1-131689510799422898" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="MEA\Arun.Viswanath" /><log4j:data name="log4net:HostName" value="IN45207575W1" /></log4j:properties><log4j:throwable>System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)</log4j:throwable></log4j:event>
<log4j:event logger="IQVIABadAPI.Controllers.HomeController" timestamp="1524479854529" level="ERROR" thread="11"><log4j:message><![CDATA[System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at IQVIABadAPI.Controllers.HomeController.LoadTweets() in C:\Projects\IQIVIABadAPI\IQIVIABadAPI\Controllers\HomeController.cs:line 39]]></log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="IN45207575W1" /><log4j:data name="log4japp" value="/LM/W3SVC/2/ROOT-1-131689510799422898" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="MEA\Arun.Viswanath" /><log4j:data name="log4net:HostName" value="IN45207575W1" /></log4j:properties><log4j:throwable>System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.38.240.145:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)</log4j:throwable></log4j:event>
